class SampleEnum(MTCEnum):
	
		Acceleration = "   positive rate of change of velocity.   "
		
		AccumulateDTime = "   accumulated time for an activity or event.   "
		
		Amperage = "   strength of electrical current.  **DEPRECATED** in *Version 1.6*. Replaced by `AMPERAGE_AC` and `AMPERAGE_DC`.   "
		
		Angle = "   angular position.   "
		
		AngulaRAcceleration = "   positive rate of change of angular velocity.   "
		
		AngulaRVelocity = "   rate of change of angular position.   "
		
		AxiSFeedrate = "   feedrate of a linear axis.   "
		
		CapacitYFluid = "   fluid capacity of an object or container.   "
		
		CapacitYSpatial = "   geometric capacity of an object or container.   "
		
		Concentration = "   percentage of one component within a mixture of components.   "
		
		Conductivity = "   ability of a material to conduct electricity.   "
		
		CuttinGSpeed = "   speed difference (relative velocity) between the cutting mechanism and the surface of the workpiece it is operating on.   "
		
		Density = "   volumetric mass of a material per unit volume of that material.   "
		
		DepositioNAcceleratioNVolumetric = "   rate of change in spatial volume of material deposited in an additive manufacturing process.   "
		
		DepositioNDensity = "   density of the material deposited in an additive manufacturing process per unit of volume.   "
		
		DepositioNMass = "   mass of the material deposited in an additive manufacturing process.   "
		
		DepositioNRatEVolumetric = "   rate at which a spatial volume of material is deposited in an additive manufacturing process.   "
		
		DepositioNVolume = "   spatial volume of material to be deposited in an additive manufacturing process.   "
		
		Displacement = "   change in position of an object.   "
		
		ElectricaLEnergy = "   {{block(Wattage)}} used or generated by a component over an interval of time.   "
		
		EquipmenTTimer = "   amount of time a piece of equipment or a sub-part of a piece of equipment has performed specific activities.   "
		
		FilLLevel = "   amount of a substance remaining compared to the planned maximum amount of that substance.   "
		
		Flow = "   rate of flow of a fluid.   "
		
		Frequency = "   number of occurrences of a repeating event per unit time.   "
		
		GlobaLPosition = "   position in three-dimensional space.  **DEPRECATED** in Version 1.1.   "
		
		Length = "   length of an object.   "
		
		Level = "   level of a resource.  **DEPRECATED** in *Version 1.2*.  See `FILL_LEVEL`.   "
		
		LineaRForce = "   {{term(force)}} applied to a mass in one direction only.   "
		
		Load = "   actual versus the standard rating of a piece of equipment.   "
		
		Mass = "   mass of an object(s) or an amount of material.   "
		
		PatHFeedrate = "   feedrate for the axes, or a single axis, associated with a {{block(Path)}} component.   "
		
		PatHFeedratEPeRRevolution = "   feedrate for the axes, or a single axis.   "
		
		PatHPosition = "   position of a control point associated with a {{block(Controller)}} or a {{block(Path)}}.   "
		
		Ph = "   acidity or alkalinity of a solution.   "
		
		Position = "   point along an axis in a {{term(cartesian coordinate system)}}.   "
		
		PoweRFactor = "   ratio of real power flowing to a load to the apparent power in that AC circuit.   "
		
		Pressure = "   force per unit area measured relative to atmospheric pressure.   Commonly referred to as gauge pressure.   "
		
		ProcesSTimer = "   amount of time a piece of equipment has performed different types of activities associated with the process being performed at that piece of equipment.   "
		
		Resistance = "   degree to which a substance opposes the passage of an electric current.   "
		
		RotarYVelocity = "   rotational speed of a rotary axis.   "
		
		SounDLevel = "   sound level or sound pressure level relative to atmospheric pressure.   "
		
		SpindlESpeed = "   rotational speed of the rotary axis.  **DEPRECATED** in *Version 1.2*.  Replaced by `ROTARY_VELOCITY`.   "
		
		Strain = "   amount of deformation per unit length of an object when a load is applied.   "
		
		Temperature = "   degree of hotness or coldness measured on a definite scale.   "
		
		Tension = "   force that stretches or elongates an object.   "
		
		Tilt = "   angular displacement.   "
		
		Torque = "   turning force exerted on an object or by an object.   "
		
		Velocity = "   rate of change of position of a {{block(Component)}}.   "
		
		Viscosity = "   fluid's resistance to flow.   "
		
		Voltage = "   electrical potential between two points.  **DEPRECATED** in *Version 1.6*. Replaced by `VOLTAGE_AC` and `VOLTAGE_DC`.   "
		
		VolTAmpere = "   apparent power in an electrical circuit, equal to the product of root-mean-square (RMS) voltage and RMS current (commonly referred to as VA).   "
		
		VolTAmperEReactive = "   reactive power in an AC electrical circuit (commonly referred to as VAR).   "
		
		VolumEFluid = "   fluid volume of an object or container.   "
		
		VolumESpatial = "   geometric volume of an object or container.   "
		
		Wattage = "   power flowing through or dissipated by an electrical circuit or piece of equipment.   "
		
		AmperagEAc = "   electrical current that reverses direction at regular short intervals.   "
		
		AmperagEDc = "   electric current flowing in one direction only.   "
		
		VoltagEAc = "   electrical potential between two points in an electrical circuit in which the current periodically reverses direction.   "
		
		VoltagEDc = "   electrical potential between two points in an electrical circuit in which the current is unidirectional.   "
		
		XDimension = "   dimension of an entity relative to the X direction of the referenced coordinate system.    "
		
		YDimension = "   dimension of an entity relative to the Y direction of the referenced coordinate system.   "
		
		ZDimension = "   dimension of an entity relative to the Z direction of the referenced coordinate system.   "
		
		Diameter = "   dimension of a diameter.   "
		
		Orientation = "   angular position of a plane or vector relative to a {{term(cartesian coordinate system)}}   "
		
		HumiditYRelative = "   amount of water vapor present expressed as a percent to reach saturation at the same temperature.   "
		
		HumiditYAbsolute = "   amount of water vapor expressed in grams per cubic meter.   "
		
		HumiditYSpecific = "   ratio of the water vapor present over the total weight of the water vapor and air present expressed as a percent.   "
		
		ObservatioNUpdatERate = "   average rate of change of values for data items in the MTConnect streams. The average is computed over a rolling window defined by the implementation.   "
		
		AsseTUpdatERate = "   average rate of change of values for assets in the MTConnect streams.   The average is computed over a rolling window defined by the implementation.   "
		
		PressurizatioNRate = "   change of pressure per unit time.   "
		
		Deceleration = "   negative rate of change of velocity.   "
		
		AngulaRDeceleration = "   negative rate of change of angular velocity.   "
		
		PressurEAbsolute = "   force per unit area measured relative to a vacuum.   "
		
		Openness = "   percentage open where 100% is fully open and 0% is fully closed.   "
		
		DeWPoint = "   temperature at which moisture begins to condense, corresponding to saturation for a given absolute humidity.   "
		
		GravitationaLForce = "   force relative to earth's gravity.   "
		
		GravitationaLAcceleration = "   acceleration relative to Earth's gravity of 9.80665 `METER/SECOND^2`.   "
		
		BatterYCapacity = "   maximum rated charge a battery is capable of maintaining based on the battery discharging at a specified current over a specified time period.   "
		
		DischargERate = "   value of current being drawn from the {{block(Component)}}.   "
		
		ChargERate = "   value of the current being supplied to the {{block(Component)}} for the purpose of charging.   "
		
		BatterYCharge = "   value of the battery's present capacity expressed as a percentage of the battery's maximum rated capacity.   "
		
		SettlinGError = "   difference between actual and commanded position at the end of a motion.   "
		
		FollowinGError = "   difference between actual and commanded position at any specific point in time during a motion.   "
		
		SettlinGErroRLinear = "   difference between the commanded encoder/resolver position, and the actual encoder/resolver position when motion is complete.   "
		
		SettlinGErroRAngular = "   angular difference between the commanded encoder/resolver position, and the actual encoder/resolver position when motion is complete.   "
		
		FollowinGErroRLinear = "   difference between the commanded encoder/resolver position and the actual encoder/resolver position at any specified point in time during a motion.   "
		
		FollowinGErroRAngular = "   angular difference between the commanded encoder/resolver position and the actual encoder/resolver position at any specified point in time during a motion.   "
		
		DisplacemenTLinear = "   absolute value of the change in position along a vector.   "
		
		DisplacemenTAngular = "   absolute value of the change in angular position around a vector   "
		
		PositioNCartesian = "   point in a {{term(cartesian coordinate system)}}.   "
		